### ISSUE TITLE
AppDelegate를 추가하는 방법이 없을까요?

### ISSUE THREAD

**Issue by leo6104** [GwonHyeok/cordova-plugin-naver#1]
private project로 개발해뒀던게 있어서 오픈소스가 없으면 공개할까 했는데 이미 이렇게 잘 만들어져있었군요 :)

잘 쓰겠습니다. :)

phonegap-plugin-push의 경우,
AppDelegate+notification.h, AppDelegate+notification.m를 구성하고 plugin.xml에 source file태그로 추가해줬던데,

이런 방법으로는 AppDelegate 코드를 패키지 설치했을 때 자동으로 되게 할 수 없을까요?

**Comment by leo6104** [comment]
https://github.com/GwonHyeok/ionic-plugin-naver/issues/1 
답변 감사합니다. 👍  Method Swizzling 으로 할 수 있군요. 
시간 될 때 fork project에서 테스트해보고 PR 올리겠습니다. :)

**Comment by GwonHyeok** [comment]
@leo6104 넵! 작업 하시게 되면 PR 해주시면 감사하겠습니다 ! ~
