### ISSUE TITLE
어떤식으로 사용하는지 예제가 있으면 좋겠네요..ㅠㅠ

### ISSUE THREAD

**Issue by sam2996** [GwonHyeok/cordova-plugin-naver#2]
코르도바 네이버 api 관련 검색하고 들어왔습니다. 

그런데 어떻게 사용해야할지 잘모르겠네요 ㅠㅠ

**Comment by leo6104** [comment]
https://github.com/GwonHyeok/cordova-plugin-naver/blob/master/README.md 
여기 설명에서 설치방법 을 읽어보세요~

**Comment by GwonHyeok** [comment]
@leo6104 답변 감사합니다..!

@sam2996 
@leo6104 님의 답변처럼 Readme.md 읽어 보시면 구현하실 수 있을 것 같습니다.

**Comment by sam2996** [comment]
@GwonHyeok

login api등 
api를 어떤 식으로 이용해야 될지 몰라서 해매고 있네요. ㅠㅠ

**Comment by sam2996** [comment]
설치는 했습니다. 

api 사용하는 방법을 잘몰라서 햇갈리네요.. 

로그인까지 완료 했습니다 그런데 이거  반환받은 데이터 토큰 같은거 어떻게 사용해야하나요..?

**Comment by GwonHyeok** [comment]
@sam2996 

`Naver.login(Function success, Function failure)`

해당 함수를 호출해서 로그인이 성공하게 되면 
success callback 으로 다음과 같은 응답이 넘어오며
```
{
    accessToken: "<long string>",
    refreshToken: "<long string>",
    expiresAt: 1500980193,
    tokenType: "bearer"
}
```

로그인이 완료된 상태에서

`Naver.requestMe(Function success, Function failure)` 함수를 호출, 성공 하면
success callback 으로 아래와 같은 응답이 넘어오게 됩니다.
```
{
    resultCode: string,
    message: string,
    response: {
        email: string,
        nickname: string,
        profileImage: string,
        age: string,
        gender: string,
        id: string,
        name: string,
        birthday: string
    }
}
```
