### ISSUE TITLE
사용법 문의 드립니다

### ISSUE THREAD

**Issue by ghost** [GwonHyeok/cordova-plugin-naver#5]
Naver.login(
    function success(result) {
        alert(result);
    },
    function failure(result) {
        alert(result);
    }
)

index.js에 위의 코드만 삽입하고 실행결과 아무런 응답을 하지 않습니다. 
추가적으로 작성해야하는 코드가 있나요?

**Comment by GwonHyeok** [comment]
네이버 개발자 계정에 등록한 애플리케이션 정보에 맞춰 패키지 명을 일치 시켜야 하며
client_id, client_secret 정보를 플러그인 설치시 정확히 적어 주셔야 합니다.

해당 정보로만 문제를 판단하기 어려우며, 조금전 테스트 결과 문제없이 실행 되었습니다.
