### ISSUE TITLE
Naver.requestMe()

### ISSUE THREAD

**Issue by teamguug** [GwonHyeok/cordova-plugin-naver#6]
Naver.requestMe() 가 작동하지 않습니다 ㅠㅠ 

사용한코드 : 
Naver.requestMe(function(res){
       alert(res)
       })
가 아무반응이없습니다 ,

Naver.login(Function success, Function failure)  성공
Naver.requestMe(Function success, Function failure) 반응없음
Naver.getState(Function success, Function failure) 성공

**Comment by GwonHyeok** [comment]
requestsMe 에서 Nullable 처리가 안되어 있어서 문제가 발생하고 있었습니다.
해당 문제수정하여 1.0.3 버전으로 업데이트 하였습니다.

감사합니다.
