### ISSUE TITLE
ios 에서 오류가납니다 ㅠ

### ISSUE THREAD

**Issue by teamguug** [GwonHyeok/cordova-plugin-naver#7]
ios 에서 구현중인데  cordova 이용 중이고 따로 AppDelegate 에 설정은 안했습니다.
네이버 로그인 클릭하면 네이버로 연결되서 아이디랑 비밀번호 치면 동의 화면까지는 나오는대 동의 누르면
어플로 리다이렉트가 안되고 그냥 네이버사이트 로 리다이렉트가 되버립니다.  
무슨 문제일까요 ㅠㅠ
그리고 xcode 에서 appdelegate 설정하라고 나와있는대 AppDelegate.m 파일에 모두 넣으면되나요?

**Comment by GwonHyeok** [comment]
@teamguug 

안녕하세요.

[URL Scheme설정](https://github.com/GwonHyeok/cordova-plugin-naver#개발제-센터-설정)

혹시 이부분 설정 하셨나요?

**Comment by teamguug** [comment]
아 네이버 앱이 설치되어있는 디바이스에서 네이버 앱으로 인증을 진행하는대 그부분에서 인증후 네이버앱초기화면으로 돌아가버리는것 같아서 무조건 사파리를 통해 인증받도록 했습니다.

**Comment by GwonHyeok** [comment]
@teamguug 네 알겠습니다

감사합니다.
